name: Terraform deployment

on:
  push:
    branches: [main, dev, sigurd_edvard]
  pull_request:
    branches: [main, dev]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform init
        run: |
          terraform init \
            -backend-config=backend.tfvars
        working-directory: ./sigurd_edvard
