name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      ARM_USE_OIDC: "true"
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_VAR_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.TF_VAR_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}

    defaults:
      run:
        working-directory: julian_magnus

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform destroy -auto-approve
